title: Bits and Bytes

name: 'Philo Vdy'
email: 'philo.vdy@gmail.com'

description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  
show_excerpts: true # set to true to show excerpts on the homepage

# generate social links in footer
social_links:
  twitter_username: jekyllrb
  github_username:  jekyll
#   rss: rss
#   twitter: jekyllrb
#   github:  jekyll
  

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.md

# Build settings
theme: minima

# plugins:
#  - jekyll-feed
#  - jekyll-seo-tag
 
 # theme: minima
# title: Bits and Bytes
# author: Philo Vdy
# email: philo.vdy@gmail.com
# description: > # this means to ignore newlines until "baseurl:"
#   Bits and Bytes, Short learnings, Code snippets from my learnings

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
# github_username:  philovdy # DO NOT include the @ character, or else the build will fail!

# show_excerpts: true # set to false to remove excerpts on the homepage
