
theme: minima
title: Bits and Bytes
author: Philo Vdy
email: philo.vdy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bits and Bytes, Short learnings, Code snippets from my learnings

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  philovdy # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
